In [ ]:
!pip install yfinance
!pip install yfinance

!pip install pandas-datareader
!pip install fix-yahoo-finance

# Import yfinance to make Yahoo Finance API call
import yfinance as yf

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import style
%matplotlib inline
import seaborn as sns
from datetime import datetime
from functools import reduce

# Import data reader to directly convert Yahoo Finance data into dataframe
from pandas_datareader import data as pdr

!pip install arch
from arch import arch_model

# ACF plot of standardized residuals
from statsmodels.graphics.tsaplots import plot_acf

# Ljunb-Box test of standardized residuals
from statsmodels.stats.diagnostic import acorr_ljungbox

from sklearn.metrics import mean_absolute_error, mean_squared_error

# Set seaborn plot style
sns.set_style("darkgrid")

# Set matplotlib plot style
style.use("fivethirtyeight")

In [ ]:
# Ignoring warning messages
import warnings
warnings.filterwarnings("ignore")

In [ ]:
from pandas_datareader import data as pdr
import fix_yahoo_finance as yf
from datetime import datetime
import yfinance as yf
import pandas_datareader.data as web

In [ ]:
# Grab data from Yahoo Finance as dataframe

yf.pdr_override() # <== that's all it takes :-)
raw_data  = pdr.get_data_yahoo('^GSPC ^GDAXI ^N225 ^FTSE', start='1994-01-07', end='2023-09-23')

raw_data

[*********************100%%**********************]  4 of 4 completed

              Adj Close                                                 Close  \
                  ^FTSE        ^GDAXI        ^GSPC         ^N225        ^FTSE
Date
1994-01-07  3446.000000   2224.949951   469.899994  18124.009766  3446.000000
1994-01-10  3440.600098   2225.000000   475.269989  18443.439453  3440.600098
1994-01-11  3413.800049   2228.100098   474.130005  18485.250000  3413.800049
1994-01-12  3372.000000   2182.060059   474.170013  18793.880859  3372.000000
1994-01-13  3360.000000   2142.370117   472.470001  18577.259766  3360.000000
...                 ...           ...          ...           ...          ...
2023-09-18  7652.899902  15727.120117  4453.529785           NaN  7652.899902
2023-09-19  7660.200195  15664.480469  4443.950195  33242.589844  7660.200195
2023-09-20  7731.700195  15781.589844  4402.200195  33023.781250  7731.700195
2023-09-21  7678.600098  15571.860352  4330.000000  32571.029297  7678.600098
2023-09-22  7683.899902  15557.290039  4320.060059  32402.410156  7683.899902

                                                            High  \
                  ^GDAXI        ^GSPC         ^N225        ^FTSE
Date
1994-01-07   2224.949951   469.899994  18124.009766  3446.800049
1994-01-10   2225.000000   475.269989  18443.439453  3468.100098
1994-01-11   2228.100098   474.130005  18485.250000  3442.500000
1994-01-12   2182.060059   474.170013  18793.880859  3402.399902
1994-01-13   2142.370117   472.470001  18577.259766  3383.300049
...                  ...          ...           ...          ...
2023-09-18  15727.120117  4453.529785           NaN  7720.100098
2023-09-19  15664.480469  4443.950195  33242.589844  7682.399902
2023-09-20  15781.589844  4402.200195  33023.781250  7741.899902
2023-09-21  15571.860352  4330.000000  32571.029297  7746.500000
2023-09-22  15557.290039  4320.060059  32402.410156  7735.200195

                          ...          Low                       Open  \
                  ^GDAXI  ...        ^GSPC         ^N225        ^FTSE
Date                      ...
1994-01-07   2227.639893  ...   467.029999  17787.480469  3401.399902
1994-01-10   2238.010010  ...   469.549988  18186.519531  3465.699951
1994-01-11   2235.610107  ...   473.269989  18373.039062  3442.500000
1994-01-12   2227.790039  ...   472.140015  18301.929688  3394.800049
1994-01-13   2183.709961  ...   471.799988  18548.750000  3380.699951
...                  ...  ...          ...           ...          ...
2023-09-18  15870.620117  ...  4442.109863           NaN  7711.399902
2023-09-19  15743.900391  ...  4416.609863  33128.859375  7652.899902
2023-09-20  15810.360352  ...  4401.379883  32988.648438  7660.200195
2023-09-21  15696.660156  ...  4329.169922  32550.650391  7731.700195
2023-09-22  15592.269531  ...  4316.490234  32154.529297  7678.600098

                                                           Volume              \
                  ^GDAXI        ^GSPC         ^N225         ^FTSE      ^GDAXI
Date
1994-01-07   2218.959961   467.089996  17842.980469  0.000000e+00         0.0
1994-01-10   2231.840088   469.899994  18186.519531  0.000000e+00         0.0
1994-01-11   2225.429932   475.269989  18481.849609  0.000000e+00         0.0
1994-01-12   2227.120117   474.130005  18447.339844  0.000000e+00         0.0
1994-01-13   2171.500000   474.170013  18770.380859  0.000000e+00         0.0
...                  ...          ...           ...           ...         ...
2023-09-18  15858.809570  4445.129883           NaN  4.633793e+08  58899600.0
2023-09-19  15688.070312  4445.410156  33296.230469  5.955460e+08  53581800.0
2023-09-20  15703.089844  4452.810059  33261.351562  8.064827e+08  54733100.0
2023-09-21  15650.980469  4374.359863  32865.558594  1.000694e+09  65995100.0
2023-09-22  15473.799805  4341.740234  32189.320312  9.896876e+08  70200200.0


                   ^GSPC        ^N225
Date
1994-01-07  3.249200e+08          0.0
1994-01-10  3.194900e+08          0.0
1994-01-11  3.054900e+08          0.0
1994-01-12  3.106900e+08          0.0
1994-01-13  2.779700e+08          0.0
...                  ...          ...
2023-09-18  3.161230e+09          NaN
2023-09-19  3.614880e+09  117200000.0
2023-09-20  3.308450e+09  113500000.0
2023-09-21  3.662340e+09  107900000.0
2023-09-22  3.349570e+09  109800000.0

[7731 rows x 24 columns]

In [ ]:
# Verifique las primeras 3 y las últimas 3 filas
pd.concat([raw_data .head(3), raw_data .tail(3)])

              Adj Close                                                 Close  \
                  ^FTSE        ^GDAXI        ^GSPC         ^N225        ^FTSE
Date
1994-01-07  3446.000000   2224.949951   469.899994  18124.009766  3446.000000
1994-01-10  3440.600098   2225.000000   475.269989  18443.439453  3440.600098
1994-01-11  3413.800049   2228.100098   474.130005  18485.250000  3413.800049
2023-09-20  7731.700195  15781.589844  4402.200195  33023.781250  7731.700195
2023-09-21  7678.600098  15571.860352  4330.000000  32571.029297  7678.600098
2023-09-22  7683.899902  15557.290039  4320.060059  32402.410156  7683.899902

                                                            High  \
                  ^GDAXI        ^GSPC         ^N225        ^FTSE
Date
1994-01-07   2224.949951   469.899994  18124.009766  3446.800049
1994-01-10   2225.000000   475.269989  18443.439453  3468.100098
1994-01-11   2228.100098   474.130005  18485.250000  3442.500000
2023-09-20  15781.589844  4402.200195  33023.781250  7741.899902
2023-09-21  15571.860352  4330.000000  32571.029297  7746.500000
2023-09-22  15557.290039  4320.060059  32402.410156  7735.200195

                          ...          Low                       Open  \
                  ^GDAXI  ...        ^GSPC         ^N225        ^FTSE
Date                      ...
1994-01-07   2227.639893  ...   467.029999  17787.480469  3401.399902
1994-01-10   2238.010010  ...   469.549988  18186.519531  3465.699951
1994-01-11   2235.610107  ...   473.269989  18373.039062  3442.500000
2023-09-20  15810.360352  ...  4401.379883  32988.648438  7660.200195
2023-09-21  15696.660156  ...  4329.169922  32550.650391  7731.700195
2023-09-22  15592.269531  ...  4316.490234  32154.529297  7678.600098

                                                           Volume              \
                  ^GDAXI        ^GSPC         ^N225         ^FTSE      ^GDAXI
Date
1994-01-07   2218.959961   467.089996  17842.980469  0.000000e+00         0.0
1994-01-10   2231.840088   469.899994  18186.519531  0.000000e+00         0.0
1994-01-11   2225.429932   475.269989  18481.849609  0.000000e+00         0.0
2023-09-20  15703.089844  4452.810059  33261.351562  8.064827e+08  54733100.0
2023-09-21  15650.980469  4374.359863  32865.558594  1.000694e+09  65995100.0
2023-09-22  15473.799805  4341.740234  32189.320312  9.896876e+08  70200200.0


                   ^GSPC        ^N225
Date
1994-01-07  3.249200e+08          0.0
1994-01-10  3.194900e+08          0.0
1994-01-11  3.054900e+08          0.0
2023-09-20  3.308450e+09  113500000.0
2023-09-21  3.662340e+09  107900000.0
2023-09-22  3.349570e+09  109800000.0

[6 rows x 24 columns]

In [ ]:
 # Crear una copia de seguridad en caso de que eliminemos/alteremos elementos de los datos por error
df_comp = raw_data.copy()
pd.concat([df_comp .head(2), df_comp .tail(2)])

              Adj Close                                                 Close  \
                  ^FTSE        ^GDAXI        ^GSPC         ^N225        ^FTSE
Date
1994-01-07  3446.000000   2224.949951   469.899994  18124.009766  3446.000000
1994-01-10  3440.600098   2225.000000   475.269989  18443.439453  3440.600098
2023-09-21  7678.600098  15571.860352  4330.000000  32571.029297  7678.600098
2023-09-22  7683.899902  15557.290039  4320.060059  32402.410156  7683.899902

                                                            High  \
                  ^GDAXI        ^GSPC         ^N225        ^FTSE
Date
1994-01-07   2224.949951   469.899994  18124.009766  3446.800049
1994-01-10   2225.000000   475.269989  18443.439453  3468.100098
2023-09-21  15571.860352  4330.000000  32571.029297  7746.500000
2023-09-22  15557.290039  4320.060059  32402.410156  7735.200195

                          ...          Low                       Open  \
                  ^GDAXI  ...        ^GSPC         ^N225        ^FTSE
Date                      ...
1994-01-07   2227.639893  ...   467.029999  17787.480469  3401.399902
1994-01-10   2238.010010  ...   469.549988  18186.519531  3465.699951
2023-09-21  15696.660156  ...  4329.169922  32550.650391  7731.700195
2023-09-22  15592.269531  ...  4316.490234  32154.529297  7678.600098

                                                           Volume              \
                  ^GDAXI        ^GSPC         ^N225         ^FTSE      ^GDAXI
Date
1994-01-07   2218.959961   467.089996  17842.980469  0.000000e+00         0.0
1994-01-10   2231.840088   469.899994  18186.519531  0.000000e+00         0.0
2023-09-21  15650.980469  4374.359863  32865.558594  1.000694e+09  65995100.0
2023-09-22  15473.799805  4341.740234  32189.320312  9.896876e+08  70200200.0


                   ^GSPC        ^N225
Date
1994-01-07  3.249200e+08          0.0
1994-01-10  3.194900e+08          0.0
2023-09-21  3.662340e+09  107900000.0
2023-09-22  3.349570e+09  109800000.0

[4 rows x 24 columns]

In [ ]:
print(df_comp.columns)

MultiIndex([('Adj Close',  '^FTSE'),
            ('Adj Close', '^GDAXI'),
            ('Adj Close',  '^GSPC'),
            ('Adj Close',  '^N225'),
            (    'Close',  '^FTSE'),
            (    'Close', '^GDAXI'),
            (    'Close',  '^GSPC'),
            (    'Close',  '^N225'),
            (     'High',  '^FTSE'),
            (     'High', '^GDAXI'),
            (     'High',  '^GSPC'),
            (     'High',  '^N225'),
            (      'Low',  '^FTSE'),
            (      'Low', '^GDAXI'),
            (      'Low',  '^GSPC'),
            (      'Low',  '^N225'),
            (     'Open',  '^FTSE'),
            (     'Open', '^GDAXI'),
            (     'Open',  '^GSPC'),
            (     'Open',  '^N225'),
            (   'Volume',  '^FTSE'),
            (   'Volume', '^GDAXI'),
            (   'Volume',  '^GSPC'),
            (   'Volume',  '^N225')],
           )

In [ ]:
df_comp

              Adj Close                                                 Close  \
                  ^FTSE        ^GDAXI        ^GSPC         ^N225        ^FTSE
Date
1994-01-07  3446.000000   2224.949951   469.899994  18124.009766  3446.000000
1994-01-10  3440.600098   2225.000000   475.269989  18443.439453  3440.600098
1994-01-11  3413.800049   2228.100098   474.130005  18485.250000  3413.800049
1994-01-12  3372.000000   2182.060059   474.170013  18793.880859  3372.000000
1994-01-13  3360.000000   2142.370117   472.470001  18577.259766  3360.000000
...                 ...           ...          ...           ...          ...
2023-09-18  7652.899902  15727.120117  4453.529785           NaN  7652.899902
2023-09-19  7660.200195  15664.480469  4443.950195  33242.589844  7660.200195
2023-09-20  7731.700195  15781.589844  4402.200195  33023.781250  7731.700195
2023-09-21  7678.600098  15571.860352  4330.000000  32571.029297  7678.600098
2023-09-22  7683.899902  15557.290039  4320.060059  32402.410156  7683.899902

                                                            High  \
                  ^GDAXI        ^GSPC         ^N225        ^FTSE
Date
1994-01-07   2224.949951   469.899994  18124.009766  3446.800049
1994-01-10   2225.000000   475.269989  18443.439453  3468.100098
1994-01-11   2228.100098   474.130005  18485.250000  3442.500000
1994-01-12   2182.060059   474.170013  18793.880859  3402.399902
1994-01-13   2142.370117   472.470001  18577.259766  3383.300049
...                  ...          ...           ...          ...
2023-09-18  15727.120117  4453.529785           NaN  7720.100098
2023-09-19  15664.480469  4443.950195  33242.589844  7682.399902
2023-09-20  15781.589844  4402.200195  33023.781250  7741.899902
2023-09-21  15571.860352  4330.000000  32571.029297  7746.500000
2023-09-22  15557.290039  4320.060059  32402.410156  7735.200195

                          ...          Low                       Open  \
                  ^GDAXI  ...        ^GSPC         ^N225        ^FTSE
Date                      ...
1994-01-07   2227.639893  ...   467.029999  17787.480469  3401.399902
1994-01-10   2238.010010  ...   469.549988  18186.519531  3465.699951
1994-01-11   2235.610107  ...   473.269989  18373.039062  3442.500000
1994-01-12   2227.790039  ...   472.140015  18301.929688  3394.800049
1994-01-13   2183.709961  ...   471.799988  18548.750000  3380.699951
...                  ...  ...          ...           ...          ...
2023-09-18  15870.620117  ...  4442.109863           NaN  7711.399902
2023-09-19  15743.900391  ...  4416.609863  33128.859375  7652.899902
2023-09-20  15810.360352  ...  4401.379883  32988.648438  7660.200195
2023-09-21  15696.660156  ...  4329.169922  32550.650391  7731.700195
2023-09-22  15592.269531  ...  4316.490234  32154.529297  7678.600098

                                                           Volume              \
                  ^GDAXI        ^GSPC         ^N225         ^FTSE      ^GDAXI
Date
1994-01-07   2218.959961   467.089996  17842.980469  0.000000e+00         0.0
1994-01-10   2231.840088   469.899994  18186.519531  0.000000e+00         0.0
1994-01-11   2225.429932   475.269989  18481.849609  0.000000e+00         0.0
1994-01-12   2227.120117   474.130005  18447.339844  0.000000e+00         0.0
1994-01-13   2171.500000   474.170013  18770.380859  0.000000e+00         0.0
...                  ...          ...           ...           ...         ...
2023-09-18  15858.809570  4445.129883           NaN  4.633793e+08  58899600.0
2023-09-19  15688.070312  4445.410156  33296.230469  5.955460e+08  53581800.0
2023-09-20  15703.089844  4452.810059  33261.351562  8.064827e+08  54733100.0
2023-09-21  15650.980469  4374.359863  32865.558594  1.000694e+09  65995100.0
2023-09-22  15473.799805  4341.740234  32189.320312  9.896876e+08  70200200.0


                   ^GSPC        ^N225
Date
1994-01-07  3.249200e+08          0.0
1994-01-10  3.194900e+08          0.0
1994-01-11  3.054900e+08          0.0
1994-01-12  3.106900e+08          0.0
1994-01-13  2.779700e+08          0.0
...                  ...          ...
2023-09-18  3.161230e+09          NaN
2023-09-19  3.614880e+09  117200000.0
2023-09-20  3.308450e+09  113500000.0
2023-09-21  3.662340e+09  107900000.0
2023-09-22  3.349570e+09  109800000.0

[7731 rows x 24 columns]

In [ ]:
# Keep only Adj Close column
df_comp = df_comp[['Adj Close']]
df_comp

              Adj Close
                  ^FTSE        ^GDAXI        ^GSPC         ^N225
Date
1994-01-07  3446.000000   2224.949951   469.899994  18124.009766
1994-01-10  3440.600098   2225.000000   475.269989  18443.439453
1994-01-11  3413.800049   2228.100098   474.130005  18485.250000
1994-01-12  3372.000000   2182.060059   474.170013  18793.880859
1994-01-13  3360.000000   2142.370117   472.470001  18577.259766
...                 ...           ...          ...           ...
2023-09-18  7652.899902  15727.120117  4453.529785           NaN
2023-09-19  7660.200195  15664.480469  4443.950195  33242.589844
2023-09-20  7731.700195  15781.589844  4402.200195  33023.781250
2023-09-21  7678.600098  15571.860352  4330.000000  32571.029297
2023-09-22  7683.899902  15557.290039  4320.060059  32402.410156

[7731 rows x 4 columns]

In [ ]:
# Renombrar  columns to the data set
df_comp= df_comp.rename(columns={"^GDAXI": " dax ", "^GSPC": "spx ", "^N225": "nikkei", "^FTSE": "ftse"})

In [ ]:
df_comp

              Adj Close
                   ftse          dax          spx         nikkei
Date
1994-01-07  3446.000000   2224.949951   469.899994  18124.009766
1994-01-10  3440.600098   2225.000000   475.269989  18443.439453
1994-01-11  3413.800049   2228.100098   474.130005  18485.250000
1994-01-12  3372.000000   2182.060059   474.170013  18793.880859
1994-01-13  3360.000000   2142.370117   472.470001  18577.259766
...                 ...           ...          ...           ...
2023-09-18  7652.899902  15727.120117  4453.529785           NaN
2023-09-19  7660.200195  15664.480469  4443.950195  33242.589844
2023-09-20  7731.700195  15781.589844  4402.200195  33023.781250
2023-09-21  7678.600098  15571.860352  4330.000000  32571.029297
2023-09-22  7683.899902  15557.290039  4320.060059  32402.410156

[7731 rows x 4 columns]

In [ ]:
print (df_comp.head()) # Displaying the first 5 elements to make sure the data was scraped correctly
print (df_comp.tail()) # Making sure the last day we're including in the series are correct

              Adj Close
                   ftse         dax         spx         nikkei
Date
1994-01-07  3446.000000  2224.949951  469.899994  18124.009766
1994-01-10  3440.600098  2225.000000  475.269989  18443.439453
1994-01-11  3413.800049  2228.100098  474.130005  18485.250000
1994-01-12  3372.000000  2182.060059  474.170013  18793.880859
1994-01-13  3360.000000  2142.370117  472.470001  18577.259766
              Adj Close
                   ftse          dax          spx         nikkei
Date
2023-09-18  7652.899902  15727.120117  4453.529785           NaN
2023-09-19  7660.200195  15664.480469  4443.950195  33242.589844
2023-09-20  7731.700195  15781.589844  4402.200195  33023.781250
2023-09-21  7678.600098  15571.860352  4330.000000  32571.029297
2023-09-22  7683.899902  15557.290039  4320.060059  32402.410156

In [ ]:
# Exportar df a Excel
df_comp.to_excel("df_comp.xlsx")